### PR TITLE
TypeScript support

### LINKED ISSUE #27: Typescript support
The types exist here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/42e3741a35ebe4b181ea80089ee960fc7fb9ae59/types/react-native/index.d.ts#L6987

(except for the new `useAsyncStorage` function)

They will need to be copied out to a separate folder (react-native-community__async-storage)

### PR DESCRIPTION
**Pull request by itsjgf**
Closes #27.

### CODE REVIEW

**Comment by Krizzu** [comment]
Hey @itsjgf, thanks for this PR!

This looks good. We're missing types for our hooks implementation - could you add them too?

Also, please move this file to `types/index.d.ts` and update `package.json` to have `"types": "./types/index.d.ts"`.


Thanks!

**Comment by itsjgf** [comment]
@Krizzu done!

**Comment by danilobuerger** [comment]
@Krizzu Would it be possible to get a release with this soon?

**Pull request merged**
